global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8081']

#scrape_configs:
#  - job_name: 'prometheus'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:8081']
#  - job_name: 'prometheus-docker'
#    scrape_interval: 5s
#    static_configs:
#      - targets: [ 'docker.for.mac.localhost:9090' ]